/**
 * WAF Detection Engine - Pure JavaScript
 * Detects WAF vendors, generates payloads, tests security
 */

// WAF vendor signatures (passive detection via headers/responses)
const WAF_SIGNATURES = {
  cloudflare: {
    headers: ['cf-ray', 'cf-request-id', '__cfduid'],
    cookies: ['__cflb', '__cfuid'],
    blockPage: ['cloudflare', 'ray id', 'attention required'],
  },
  aws_waf: {
    headers: ['x-amzn-requestid', 'x-amz-cf-id'],
    blockPage: ['request blocked'],
  },
  imperva: {
    headers: ['x-iinfo', 'x-cdn'],
    cookies: ['incap_ses', 'visid_incap'],
    blockPage: ['incapsula', '_incident_id'],
  },
  akamai: {
    headers: ['akamai-origin-hop', 'akamai-cache-status'],
    blockPage: ['akamai', 'reference #'],
  },
  f5_asm: {
    headers: ['x-wa-info'],
    cookies: ['TS'],
    blockPage: ['the requested url was rejected'],
  },
  modsecurity: {
    blockPage: ['mod_security', 'this error was generated by mod_security'],
  },
  sucuri: {
    headers: ['x-sucuri-id', 'x-sucuri-cache'],
    blockPage: ['sucuri website firewall'],
  },
  wordfence: {
    headers: ['wordfence'],
    blockPage: ['generated by wordfence'],
  },
};

// Attack payloads by category (offline, no external fetch)
const PAYLOADS = {
  sql_injection: [
    "' OR '1'='1",
    "1' UNION SELECT NULL--",
    "admin'--",
    "' OR 1=1--",
    "1' AND 1=0 UNION ALL SELECT 'admin', 'pass'--",
  ],
  xss: [
    '<script>alert(1)</script>',
    '<img src=x onerror=alert(1)>',
    '<svg/onload=alert(1)>',
    'javascript:alert(1)',
    '<iframe src=javascript:alert(1)>',
  ],
  path_traversal: [
    '../../../etc/passwd',
    '..\\..\\..\\windows\\system.ini',
    '/etc/passwd',
    '....//....//....//etc/passwd',
  ],
  command_injection: [
    '; ls -la',
    '| whoami',
    '`cat /etc/passwd`',
    '$( cat /etc/passwd )',
  ],
  ssrf: [
    'http://169.254.169.254/latest/meta-data/',
    'http://localhost:22',
    'file:///etc/passwd',
  ],
  lfi: [
    'php://filter/convert.base64-encode/resource=index.php',
    'file:///etc/passwd',
    'expect://ls',
  ],
};

/**
 * Detects WAF presence and type
 */
export async function detectWAF(url) {
  const result = {
    detected: false,
    type: null,
    confidence: 0,
    method: null,
    evidence: [],
  };

  try {
    // Phase 1: Passive detection (headers)
    const response = await fetch(url, {
      headers: { 'User-Agent': 'Mozilla/5.0 (WAF-Scanner/1.0)' },
    });

    const headers = Object.fromEntries(response.headers.entries());
    const cookies = headers['set-cookie'] || '';

    for (const [vendor, sigs] of Object.entries(WAF_SIGNATURES)) {
      let score = 0;

      // Check headers
      if (sigs.headers) {
        for (const header of sigs.headers) {
          if (headers[header] || headers[header.toLowerCase()]) {
            score += 30;
            result.evidence.push(`Header: ${header}`);
          }
        }
      }

      // Check cookies
      if (sigs.cookies) {
        for (const cookie of sigs.cookies) {
          if (cookies.includes(cookie)) {
            score += 20;
            result.evidence.push(`Cookie: ${cookie}`);
          }
        }
      }

      if (score >= 30) {
        result.detected = true;
        result.type = vendor;
        result.confidence = Math.min(score, 100);
        result.method = 'passive';
        break;
      }
    }

    // Phase 2: Active detection (trigger with probe)
    if (!result.detected) {
      const probeUrl = url + '?test=' + encodeURIComponent("' OR 1=1--");
      const probeResp = await fetch(probeUrl);
      const bodyText = await probeResp.text();

      for (const [vendor, sigs] of Object.entries(WAF_SIGNATURES)) {
        if (sigs.blockPage) {
          for (const pattern of sigs.blockPage) {
            if (bodyText.toLowerCase().includes(pattern.toLowerCase())) {
              result.detected = true;
              result.type = vendor;
              result.confidence = 70;
              result.method = 'active';
              result.evidence.push(`Block page: "${pattern}"`);
              break;
            }
          }
        }
        if (result.detected) break;
      }
    }
  } catch (error) {
    console.error('WAF detection error:', error.message);
  }

  return result;
}

/**
 * Generates encoded/obfuscated payload variants
 */
export function generateBypassVariants(payload, type) {
  const variants = [payload]; // Original

  if (type === 'sql_injection') {
    // SQL obfuscation
    variants.push(payload.replace(/ /g, '/**/')); // Comment spaces
    variants.push(payload.replace(/ /g, '%09')); // Tab instead of space
    variants.push(payload.replace(/OR/gi, '||')); // Logical OR operator
    variants.push(payload.toUpperCase()); // Case variation
    variants.push(payload.toLowerCase());
  }

  if (type === 'xss') {
    // XSS obfuscation
    variants.push(payload.replace(/<script>/gi, '<ScRiPt>')); // Mixed case
    variants.push(payload.replace(/alert/g, 'prompt')); // Function variant
    variants.push(encodeURIComponent(payload)); // URL encoding
    variants.push(payload.replace(/ /g, '/**/')); // Comment injection
  }

  // Universal encodings
  variants.push(encodeURIComponent(encodeURIComponent(payload))); // Double URL encode
  variants.push(Buffer.from(payload).toString('base64')); // Base64

  return [...new Set(variants)]; // Remove duplicates
}

/**
 * Tests a single payload against URL
 */
export async function testPayload(url, payload, category, timeout = 60000) {
  const result = {
    payload,
    category,
    blocked: false,
    status: null,
    responseTime: 0,
    error: null,
    timedOut: false,
  };

  try {
    const testUrl = url + (url.includes('?') ? '&' : '?') + 'test=' + encodeURIComponent(payload);
    const startTime = Date.now();

    // Timeout protection using AbortController
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), timeout);

    try {
      const response = await fetch(testUrl, {
        headers: { 'User-Agent': 'Mozilla/5.0' },
        redirect: 'manual',
        signal: controller.signal,
      });

      clearTimeout(timeoutId);
      result.responseTime = Date.now() - startTime;
      result.status = response.status;

      // Blocked indicators: 403, 406, 429, redirects to block pages
      if ([403, 406, 429, 503].includes(response.status)) {
        result.blocked = true;
      } else if ([301, 302, 307, 308].includes(response.status)) {
        const location = response.headers.get('location') || '';
        if (location.includes('block') || location.includes('denied')) {
          result.blocked = true;
        }
      }
    } catch (err) {
      clearTimeout(timeoutId);

      if (err.name === 'AbortError') {
        // Timeout occurred
        result.error = `Request timeout after ${timeout}ms`;
        result.timedOut = true;
        result.blocked = true; // Assume blocked if timeout
      } else {
        throw err;
      }
    }
  } catch (error) {
    result.error = error.message;
    result.blocked = true; // Assume blocked if request fails
  }

  return result;
}

/**
 * Self-audit Agent Player backend security (ENHANCED - Phase 5)
 * Comprehensive security assessment with 14 headers + 6 advanced tests
 */
export async function selfAudit(backendUrl) {
  const issues = [];
  let securityScore = 100; // Start with perfect score

  try {
    // ========================================================================
    // TEST GROUP 1: Security Headers (14 headers)
    // ========================================================================

    const response = await fetch(backendUrl + '/api/database/stats');
    const headers = Object.fromEntries(response.headers.entries());

    // 1. X-Content-Type-Options
    if (!headers['x-content-type-options'] || headers['x-content-type-options'] !== 'nosniff') {
      issues.push({
        severity: 'medium',
        type: 'Missing Security Header',
        detail: 'X-Content-Type-Options header not set to "nosniff"',
        recommendation: 'Add header: X-Content-Type-Options: nosniff',
        points: 2,
      });
      securityScore -= 2;
    }

    // 2. X-Frame-Options
    if (!headers['x-frame-options']) {
      issues.push({
        severity: 'medium',
        type: 'Missing Security Header',
        detail: 'X-Frame-Options header not set (clickjacking risk)',
        recommendation: 'Add header: X-Frame-Options: DENY or SAMEORIGIN',
        points: 2,
      });
      securityScore -= 2;
    }

    // 3. Strict-Transport-Security (HSTS)
    if (!headers['strict-transport-security']) {
      issues.push({
        severity: 'low',
        type: 'Missing Security Header',
        detail: 'HSTS not enabled (acceptable for localhost)',
        recommendation: 'Add HSTS in production: Strict-Transport-Security: max-age=31536000; includeSubDomains',
        points: 1,
      });
      securityScore -= 1;
    }

    // 4. Content-Security-Policy
    if (!headers['content-security-policy']) {
      issues.push({
        severity: 'medium',
        type: 'Missing Security Header',
        detail: 'Content-Security-Policy header not set (XSS risk)',
        recommendation: 'Add CSP: Content-Security-Policy: default-src \'self\'; script-src \'self\'',
        points: 2,
      });
      securityScore -= 2;
    }

    // 5. X-XSS-Protection
    if (!headers['x-xss-protection']) {
      issues.push({
        severity: 'low',
        type: 'Missing Security Header',
        detail: 'X-XSS-Protection header not set',
        recommendation: 'Add header: X-XSS-Protection: 1; mode=block',
        points: 1,
      });
      securityScore -= 1;
    }

    // 6. Referrer-Policy
    if (!headers['referrer-policy']) {
      issues.push({
        severity: 'low',
        type: 'Missing Security Header',
        detail: 'Referrer-Policy header not set',
        recommendation: 'Add header: Referrer-Policy: no-referrer or strict-origin-when-cross-origin',
        points: 1,
      });
      securityScore -= 1;
    }

    // 7. Permissions-Policy
    if (!headers['permissions-policy']) {
      issues.push({
        severity: 'low',
        type: 'Missing Security Header',
        detail: 'Permissions-Policy header not set',
        recommendation: 'Add header: Permissions-Policy: geolocation=(), microphone=(), camera=()',
        points: 1,
      });
      securityScore -= 1;
    }

    // 8. X-DNS-Prefetch-Control
    if (!headers['x-dns-prefetch-control']) {
      issues.push({
        severity: 'low',
        type: 'Missing Security Header',
        detail: 'X-DNS-Prefetch-Control header not set',
        recommendation: 'Add header: X-DNS-Prefetch-Control: off',
        points: 1,
      });
      securityScore -= 1;
    }

    // 9. X-Download-Options
    if (!headers['x-download-options']) {
      issues.push({
        severity: 'low',
        type: 'Missing Security Header',
        detail: 'X-Download-Options header not set',
        recommendation: 'Add header: X-Download-Options: noopen',
        points: 1,
      });
      securityScore -= 1;
    }

    // 10. X-Permitted-Cross-Domain-Policies
    if (!headers['x-permitted-cross-domain-policies']) {
      issues.push({
        severity: 'low',
        type: 'Missing Security Header',
        detail: 'X-Permitted-Cross-Domain-Policies header not set',
        recommendation: 'Add header: X-Permitted-Cross-Domain-Policies: none',
        points: 1,
      });
      securityScore -= 1;
    }

    // 11. Cross-Origin-Embedder-Policy
    if (!headers['cross-origin-embedder-policy']) {
      issues.push({
        severity: 'low',
        type: 'Missing Security Header',
        detail: 'Cross-Origin-Embedder-Policy header not set',
        recommendation: 'Add header: Cross-Origin-Embedder-Policy: require-corp',
        points: 1,
      });
      securityScore -= 1;
    }

    // 12. Cross-Origin-Opener-Policy
    if (!headers['cross-origin-opener-policy']) {
      issues.push({
        severity: 'low',
        type: 'Missing Security Header',
        detail: 'Cross-Origin-Opener-Policy header not set',
        recommendation: 'Add header: Cross-Origin-Opener-Policy: same-origin',
        points: 1,
      });
      securityScore -= 1;
    }

    // 13. Cross-Origin-Resource-Policy
    if (!headers['cross-origin-resource-policy']) {
      issues.push({
        severity: 'low',
        type: 'Missing Security Header',
        detail: 'Cross-Origin-Resource-Policy header not set',
        recommendation: 'Add header: Cross-Origin-Resource-Policy: same-origin',
        points: 1,
      });
      securityScore -= 1;
    }

    // 14. Cache-Control (sensitive data)
    if (!headers['cache-control'] || !headers['cache-control'].includes('no-store')) {
      issues.push({
        severity: 'medium',
        type: 'Insecure Caching',
        detail: 'Cache-Control header does not prevent sensitive data caching',
        recommendation: 'Add header: Cache-Control: no-store, no-cache, must-revalidate, private',
        points: 2,
      });
      securityScore -= 2;
    }

    // ========================================================================
    // TEST GROUP 2: CORS Configuration
    // ========================================================================

    const corsTest = await fetch(backendUrl + '/api/database/stats', {
      headers: { 'Origin': 'https://evil.com' },
    });
    const corsHeaders = Object.fromEntries(corsTest.headers.entries());

    if (corsHeaders['access-control-allow-origin'] === '*') {
      issues.push({
        severity: 'high',
        type: 'CORS Misconfiguration',
        detail: 'CORS allows all origins (wildcard)',
        recommendation: 'Restrict CORS to specific origins (http://localhost:41521)',
        points: 3,
      });
      securityScore -= 3;
    }

    // ========================================================================
    // TEST GROUP 3: SQL Injection Testing (on own endpoints)
    // ========================================================================

    const sqlPayloads = [
      "' OR '1'='1",
      "1' UNION SELECT NULL--",
      "admin'--",
    ];

    for (const payload of sqlPayloads) {
      try {
        // Test if endpoint is vulnerable to SQL injection
        const sqlTest = await fetch(`${backendUrl}/api/database/stats?test=${encodeURIComponent(payload)}`);
        const sqlText = await sqlTest.text();

        // Check for SQL error messages (indicates vulnerability)
        if (sqlText.includes('SQLITE_ERROR') || sqlText.includes('syntax error') || sqlText.includes('near')) {
          issues.push({
            severity: 'critical',
            type: 'SQL Injection Vulnerability',
            detail: `Endpoint vulnerable to SQL injection with payload: ${payload}`,
            recommendation: 'Use parameterized queries and input validation',
            points: 5,
          });
          securityScore -= 5;
          break; // Only report once
        }
      } catch (e) {
        // Ignore fetch errors
      }
    }

    // ========================================================================
    // TEST GROUP 4: Authentication Bypass Testing
    // ========================================================================

    try {
      // Try to access protected endpoint without token
      const authTest = await fetch(backendUrl + '/api/agents');
      if (authTest.status === 200) {
        issues.push({
          severity: 'critical',
          type: 'Authentication Bypass',
          detail: 'Protected endpoint /api/agents accessible without authentication',
          recommendation: 'Enforce JWT authentication on all protected routes',
          points: 5,
        });
        securityScore -= 5;
      }
    } catch (e) {
      // Ignore fetch errors
    }

    // ========================================================================
    // TEST GROUP 5: Rate Limiting Testing
    // ========================================================================

    let rateLimitWorks = false;
    try {
      // Send 15 rapid requests
      const requests = [];
      for (let i = 0; i < 15; i++) {
        requests.push(fetch(backendUrl + '/api/database/stats'));
      }

      const results = await Promise.all(requests);
      const tooManyRequests = results.filter(r => r.status === 429);

      if (tooManyRequests.length === 0) {
        issues.push({
          severity: 'medium',
          type: 'Missing Rate Limiting',
          detail: 'No rate limiting detected on API endpoints',
          recommendation: 'Implement rate limiting (e.g., 100 requests per minute per IP)',
          points: 2,
        });
        securityScore -= 2;
      } else {
        rateLimitWorks = true;
      }
    } catch (e) {
      // Ignore fetch errors
    }

    // ========================================================================
    // TEST GROUP 6: Error Information Disclosure
    // ========================================================================

    const errorTest = await fetch(backendUrl + '/api/invalid-endpoint-xyz-123');
    const errorText = await errorTest.text();

    if (errorText.includes('at ') || errorText.includes('.ts:') || errorText.includes('.js:')) {
      issues.push({
        severity: 'low',
        type: 'Information Disclosure',
        detail: 'Stack traces exposed in error responses',
        recommendation: 'Disable stack traces in production (NODE_ENV=production)',
        points: 1,
      });
      securityScore -= 1;
    }

    // ========================================================================
    // TEST GROUP 7: Session Management (JWT)
    // ========================================================================

    // Check if server validates JWT expiration
    // This is a placeholder - would need actual expired token to test
    // For now, we just recommend best practices

  } catch (error) {
    console.error('Self-audit error:', error.message);
    issues.push({
      severity: 'high',
      type: 'Audit Failure',
      detail: `Self-audit failed: ${error.message}`,
      recommendation: 'Investigate audit failure - backend may be unreachable',
      points: 3,
    });
    securityScore -= 3;
  }

  // Calculate final security score (0-100)
  securityScore = Math.max(0, Math.min(100, securityScore));

  return {
    securityScore,
    grade: getSecurityGrade(securityScore),
    totalIssues: issues.length,
    criticalSeverity: issues.filter(i => i.severity === 'critical').length,
    highSeverity: issues.filter(i => i.severity === 'high').length,
    mediumSeverity: issues.filter(i => i.severity === 'medium').length,
    lowSeverity: issues.filter(i => i.severity === 'low').length,
    issues,
    summary: generateAuditSummary(issues, securityScore),
  };
}

/**
 * Get security grade from score
 * @param {number} score - Security score (0-100)
 * @returns {string} Grade
 */
function getSecurityGrade(score) {
  if (score >= 95) return 'A+';
  if (score >= 90) return 'A';
  if (score >= 80) return 'B';
  if (score >= 70) return 'C';
  if (score >= 60) return 'D';
  return 'F';
}

/**
 * Generate audit summary
 * @param {array} issues - List of issues
 * @param {number} score - Security score
 * @returns {object} Summary
 */
function generateAuditSummary(issues, score) {
  const critical = issues.filter(i => i.severity === 'critical').length;
  const high = issues.filter(i => i.severity === 'high').length;

  let status = 'Excellent';
  let message = 'Your backend security is excellent';

  if (critical > 0) {
    status = 'Critical';
    message = `${critical} critical security issues found - immediate action required`;
  } else if (high > 0) {
    status = 'Poor';
    message = `${high} high-severity issues found - action needed`;
  } else if (score >= 90) {
    status = 'Excellent';
    message = 'Your backend security is excellent';
  } else if (score >= 70) {
    status = 'Good';
    message = 'Your backend security is good with minor improvements needed';
  } else {
    status = 'Fair';
    message = 'Your backend security needs improvement';
  }

  return {
    status,
    message,
    topIssues: issues
      .sort((a, b) => (b.points || 0) - (a.points || 0))
      .slice(0, 3)
      .map(i => i.detail),
  };
}

/**
 * Load payloads from database (NEW - Phase 2.2)
 * @param {object} db - Database instance
 * @param {string|null} category - Filter by category (null = all)
 * @param {boolean} includeEvasions - Include evasion technique payloads
 * @returns {array} Array of payload objects
 */
export function getPayloadsFromDatabase(db, category = null, includeEvasions = true) {
  try {
    let query = 'SELECT * FROM waf_payload_library WHERE 1=1';
    const params = [];

    if (category) {
      query += ' AND category = ?';
      params.push(category);
    }

    if (!includeEvasions) {
      query += ' AND evasion_technique = "none"';
    }

    query += ' ORDER BY severity DESC, category ASC';

    const stmt = db.prepare(query);
    const results = stmt.all(...params);

    return results;
  } catch (error) {
    console.error('Database payload loading error:', error.message);
    return [];
  }
}

/**
 * Get all payload categories from database
 * @param {object} db - Database instance
 * @returns {array} Array of category objects with counts
 */
export function getPayloadCategoriesFromDatabase(db) {
  try {
    const results = db.prepare(`
      SELECT
        category,
        COUNT(*) as count,
        SUM(CASE WHEN severity = 'critical' THEN 1 ELSE 0 END) as critical_count,
        SUM(CASE WHEN severity = 'high' THEN 1 ELSE 0 END) as high_count
      FROM waf_payload_library
      GROUP BY category
      ORDER BY category ASC
    `).all();

    return results.map(row => ({
      id: row.category,
      name: row.category.replace(/_/g, ' ').toUpperCase(),
      count: row.count,
      criticalCount: row.critical_count,
      highCount: row.high_count,
    }));
  } catch (error) {
    console.error('Database category loading error:', error.message);
    return [];
  }
}

/**
 * Get all payload categories (LEGACY - fallback to database)
 */
export function getPayloadCategories(db = null) {
  // Try database first
  if (db) {
    const dbCategories = getPayloadCategoriesFromDatabase(db);
    if (dbCategories.length > 0) {
      return dbCategories;
    }
  }

  // Fallback to hardcoded payloads
  return Object.keys(PAYLOADS).map(key => ({
    id: key,
    name: key.replace(/_/g, ' ').toUpperCase(),
    count: PAYLOADS[key].length,
  }));
}

/**
 * Get payloads for specific category (LEGACY - fallback to database)
 */
export function getPayloads(category, db = null) {
  // Try database first
  if (db) {
    const dbPayloads = getPayloadsFromDatabase(db, category, true);
    if (dbPayloads.length > 0) {
      // Convert to simple string array for backward compatibility
      return dbPayloads.map(p => p.payload);
    }
  }

  // Fallback to hardcoded payloads
  return PAYLOADS[category] || [];
}
